ports:
  - name: Site
    description: Site
    onOpen: open-browser
    port: 5000
    visibility: public
    protocol: https

tasks:
  - before: cd .venv/bin
    command: |
      pip install -r requirements.txt
      python app.py
